### PR TITLE
Edge detection

### PR DESCRIPTION
**Pull request by orsoromeo**
I added two new packages to this repo:
* edge_detection
* edge_detection_ros

External dependencies:
* Rviz Visual Tools: https://github.com/PickNikRobotics/rviz_visual_tools
* Locomotion Viewer: https://github.com/iit-DLSLab/locomotion-viewer

How to test it:
* run simulation with elevation map and then:
* `rosrun edge_detection_ros edge_detection_ros`

### CODE REVIEW

**Comment by mauricefallon** [comment]
I tried to compile this but it's missing the following:
- eigen_stl_containers
- graph_msgs

I tried to compile these but eigen_stl_containers isnt compiling properly. Can you explain how do get these.?


I cannot merge in an edge detector that is dependent on 4 dependencies to draw simple MarkerArrays.

**Comment by orsoromeo** [comment]
Have you already tried running:
```
sudo apt install ros-melodic-eigen-stl-containers
sudo apt install ros-melodic-graph-msgs
```
Locomotion-viewer is supposed to be a conveniency to write MarkerArrays using Eigen and it allows to draw segments and paths as sequences of vertices (Vector3d) rather than providing the pose of each cylinder marker. But if you think that these 4 dependencies are too much then I can remove the locomotion-viewer dependency from this package.

**Comment by mauricefallon** [comment]
> But if you think that these 4 dependencies are too much then I can remove the locomotion-viewer dependency from this package.

Please do this. We dont need new dependencies to draw simple lines.

I could build the code and run it on the default simulator:
image

I dont think either of us will make any progress on this over email. I can discuss with you in person or on a call.

My preference is to go directly to real data. It's not worthwhile to develop perception using perfect simulated terrain data IMO.

**Comment by orsoromeo** [comment]
I spent some time tuning the parameters of the edge detector on the bag file collected on Anymal C:
https://drive.google.com/file/d/1wIcW0aPcMIs9dfRAgIUmoUPH6rWsUmCH/view?usp=sharing
This is how it looks:
image

Ok, as regards the dependencies. I will fix it ASAP.

**Comment by orsoromeo** [comment]
I have removed the dependency from LocomotionViewer in the `edge-detection` branch as requested and all the rviz plotting is now done through standard markers. This removes the dependency from` ros-melodic-eigen-stl-containers` and `ros-melodic-graph-msgs` too. 

Please notice that I also removed the dependency from the `anymal_msgs` and from the `xpp_msgs` that we use to update the robot state on the robot and in simulation respectively. These were used to sort the detected edges with increasing distance from the robot and to know which is the "next" edge in front of the robot. Because these have been deleted then the edges will be ordered with increasing distance from the origin of the map frame. If anyone wants to bring back this functionality s/he will have to fill the `base_pose_` variable listening to its custom ros message.

**Comment by mauricefallon** [comment]
can you create a video of the performance of both this and elevation mapping (for ANYmal with real data)
so I see the performance before merging. also want to share with LAAS

Something like this:
https://www.youtube.com/watch?v=YYs4lJ9t-Xo

**Comment by orsoromeo** [comment]
Here is the  [video](https://drive.google.com/file/d/1rDWeL5DDdWON0Rp-FGkdsmAEQz6jwUDD/view?usp=sharing) of the performances of the elevation map and the edge detection.
The log was recorded while performing a walk gait with TOWR-MPC so I would say that the motion is fairly dynamic (the base moves a lot). The elevation map is updated at 0.5 Hz and only the front camera is used at the moment.

**Comment by mauricefallon** [comment]
thanks @orsoromeo . that video is great. I'll merge this.

FYI: @mcamurri @TLasguignes  and @ChristosIoannou :
this will be useful and can be used for the staircase edge detection.

**Pull request merged**
